apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}-monitoring
  labels:
    app: {{ include "mychart.name" . }}
    tier: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mychart.name" . }}
      tier: monitoring
  template:
    metadata:
      labels:
        app: {{ include "mychart.name" . }}
        tier: monitoring
    spec:
      containers:
      - name: monitoring
        image: {{ .Values.monitoring.image }}
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
