apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-redis-exporter
  labels:
    app: {{ include "mychart.name" . }}
    tier: redis-exporter
spec:
  ports:
    - port: 9121
      targetPort: 9121
  selector:
    app: {{ include "mychart.name" . }}
    tier: redis-exporter
