apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-blackbox-exporter
  labels:
    app: {{ include "mychart.name" . }}
    tier: blackbox-exporter
spec:
  ports:
    - port: 9115
      targetPort: 9115
  selector:
    app: {{ include "mychart.name" . }}
    tier: blackbox-exporter
