apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-grafana
  labels:
    app: {{ include "mychart.name" . }}
    tier: grafana
spec:
  ports:
    - port: 3001
      targetPort: 3000
  selector:
    app: {{ include "mychart.name" . }}
    tier: grafana
