apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-monitoring
  labels:
    app: {{ include "mychart.name" . }}
    tier: monitoring
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: {{ include "mychart.name" . }}
    tier: monitoring
