apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-web
  labels:
    app: {{ include "mychart.name" . }}
    tier: web
spec:
  ports:
    - port: 3000
      targetPort: 8080
  selector:
    app: {{ include "mychart.name" . }}
    tier: web
