apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://monitoring:9090  # Use the service name and port where Prometheus is running
  basicAuth: false
  isDefault: true
  editable: true
